package DataPreparation;

import org.apache.log4j.Level;
import org.apache.log4j.Logger;

import org.apache.spark.SparkConf;
import org.apache.spark.api.java.JavaRDD;
import org.apache.spark.api.java.JavaSparkContext;
import org.apache.spark.sql.Dataset;
import org.apache.spark.sql.Row;

public class SparkMain {
    private static final String jobPath = "src/main/resources/data/Wuzzuf_Jobs.csv";

    public static void main(String[] args) {

        //omit the log generated by apache spark from the output.
        Logger.getLogger ("org").setLevel (Level.ERROR);
        SparkDAO dao = new SparkDAO();

        //create dataset & it's schema
        Dataset<Row> jobDataset = dao.readCSV(jobPath);



        }
}
